### ISSUE TITLE
Getter for Kelvin, Celcius, etc 

### ISSUE THREAD

**Issue by hpsaturn** [kike-canaries/canairio_sensorlib#116]
**Summary.**

For imperial or metrics units maybe we need specialized getters

Discussion: https://t.me/canairio/20267

**Comment by jcomas** [comment]
Suggestions for a temperature sensor:
`sensor.getTemperatureRaw()`
`sensor.getTemperatureCelsius()`
`sensor.getTemperatureFahrenheit()`
`sensor.getTemperatureKelvin()`

**Comment by hpsaturn** [comment]
resolved in the next PR #176
