### ISSUE TITLE
[sps30] why the sps30 values was rounded?

### ISSUE THREAD

**Issue by hpsaturn** [kike-canaries/canairio_sensorlib#13]
**Description**

The current CanAirIO sensorlib implementation, and old versions had a:

```javascript
pm25 = round(val.MassPM2);
```

Maybe the library should give the raw values from the original sps30 library?

**Comment by danielbernalb** [comment]
the value of val.MassPM2 is float and is the raw value, this is converted to int and rounded

**Comment by arttesano** [comment]
I'm going to ask an expert

**Comment by hpsaturn** [comment]
The last version refactored these methods.
