### ISSUE TITLE
I2c implementation

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_sensorlib#51]
Development of i2c communication and thus be able to connect several sensors with the same device.
I am thinking about MHZ19 by uart, and PM2.5, Tvoc, Temperature, humidity, etc... by i2c.

**Comment by hpsaturn** [comment]
The PM2.5 sensor is a SPS30? or which sensor?

**Comment by roberbike** [comment]
> Thanks for the request. The PM2.5 sensor is a SPS30? or which sensor?

Yes, it is a sensirion sps30.
