### ISSUE TITLE
SPS30i2c Fail to read measurements

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_sensorlib#73]
When a sensirion sps30 device is coneccted to i2c , the firmware only shows the first data read. Do not refresh the values anymore

**Comment by BRKMK** [comment]
Updated firmware 781 to 785 via OTA, and sensor is not detected by i2c .

**Comment by hpsaturn** [comment]
for now, any official OTA version has not the i2c implementation. When we resolved all issues with i2c, I will released a new CanAirIO firmware with it

**Comment by roberbike** [comment]
Add  u8g2.setBusClock(100000);   solved the issue
