### ISSUE TITLE
BATT charge level appears every second instead sample time via serial

### ISSUE THREAD

**Issue by danielbernalb** [kike-canaries/canairio_sensorlib#9]
Serial output:
__-->[BATT] chargelevel: 0%
-->[HPMA] read > done! PM1:000 PM25:000 PM10:000 H:00% T:00°C
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[HPMA] read > done! PM1:000 PM25:000 PM10:000 H:00% T:00°C
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[BATT] chargelevel: 0%
-->[HPMA] read > done! PM1:000 PM25:000 PM10:000 H:00% T:00°C_
-->[BATT] chargelevel: 0%_

**Comment by hpsaturn** [comment]
Thanks for report it but this issue is from `canairio_firmware` repo, the battery level for now, is handled by the main firmware, the sensorlib can't using the battery.

**Comment by hpsaturn** [comment]
I'm going to close this issue because is for `canairio_firmware` repo. Please report it in that repo.
