### ISSUE TITLE
SN-GCJA5 PM 10 does not show

### ISSUE THREAD

**Issue by roberbike** [kike-canaries/canairio_sensorlib#93]
PM 10 values of panasonic SN-GCJA5 is not showed.
Sensor conected by i2c,  The rest of the values, PM 1 and PM 2.5 are recorded.

**To Reproduce**
By serial debug PM 10 value is always 0000.
App show the same data, 0

TTgo T 7 + Oled
Debug mode  ON

The sensor was tested with samples from the paulvha/SN-GCJA5 library and works perfectly.

-->[SLIB] UART sensors count:  0
-->[SLIB] GCJA5 read > done! 
-->[SLIB] PM1:012 PM25:008 PM10:000 CO2:0000 CO2humi:0.000000% CO2temp:0.000000°C H:0.000000% T:0.000000°C
-->[SLIB] no data on UART port 
-->[SLIB] UART sensors count:  0
-->[SLIB] GCJA5 read > done! 
-->[SLIB] PM1:019 PM25:008 PM10:000 CO2:0000 CO2humi:0.000000% CO2temp:0.000000°C H:0.000000% T:0.000000°C
-->[IFDB] write done.
-->[SLIB] no data on UART port 
-->[SLIB] UART sensors count:  0
-->[SLIB] GCJA5 read > done! 
-->[SLIB] PM1:012 PM25:001 PM10:000 CO2:0000 CO2humi:0.000000% CO2temp:0.000000°C H:0.000000% T:0.000000°C
-->[SLIB] no data on UART port 
-->[SLIB] UART sensors count:  0
-->[SLIB] GCJA5 read > done! 
-->[SLIB] PM1:017 PM25:002 PM10:000 CO2:0000 CO2humi:0.000000% CO2temp:0.000000°C H:0.000000% T:0.000000°C
-->[IFDB] write done.
-->[SLIB] no data on UART port 
-->[SLIB] UART sensors count:  0
-->[SLIB] GCJA5 read > done! 
-->[SLIB] PM1:017 PM25:001 PM10:000 CO2:0000 CO2humi:0.000000% CO2temp:0.000000°C H:0.000000% T:0.000000°C
-->[SLIB] no data on UART port 
-->[SLIB] UART sensors count:  0

**Comment by hpsaturn** [comment]
I deployed on dev channel a firmware with this issue fix, please test it
