### ISSUE TITLE
Altitude compensation bug

### ISSUE THREAD

**Issue by danielbernalb** [kike-canaries/canairio_sensorlib#98]
**Describe the bug**
In the case of the SCD30 sensor the library erase the original value that the sensor have in memory.
The app have problems of sincronization with the value of altitude that the sensor have in memory.

**To Reproduce**
1. Use a SCD30 with a valur of altitude different to zero.
2. Start the library example
3. The value of the SCD30 is erased

**Additional context**

**Comment by hpsaturn** [comment]
please paste the example code that you are using for the test.

**Comment by hpsaturn** [comment]
closed with PR #100
